### ISSUE TITLE
music error

### ISSUE THREAD

**Issue by Ariz-z** [napstr/Magma#31]
```3|start  | 2020-05-11 07:34:32.450  INFO 25700 --- [     parallel-2] s.n.m.impl.connections.AudioWebSocket    : Websocket to wss://india715.discord.media/?v=4 closed with code 4006 and reason Session is no longer valid.
3|start  | 2020-05-11 07:34:32.450  WARN 25700 --- [     parallel-2] s.n.m.impl.connections.AudioWebSocket    : Connection closed due to [4006 SESSION_NO_LONGER_VALID] Session is no longer valid.. This could indicate an issue with the magma library or your usage of it. Please get in touch. https://github.com/napstr/Magma/issues
3|start  | 2020-05-11 07:34:32.451  INFO 25700 --- [     parallel-2] s.n.m.impl.connections.AudioWebSocket    : Closing
``` please help me

**Comment by schnapster** [comment]
[Close code 4006 means your session became invalid](https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes). Most of the time this is because your Discord library opened a second voice connection, or your usage of a Lavalink client lead to a second voice connection being opened. In any case it is very unlikely an issue with the Magma library. If you continue having trouble with this, ask for help with the person that implemented your client or in the Lavalink Discord channel.
